steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build-blue
  args:
  - 'build'
  - '-t'
  - 'europe-west1-docker.pkg.dev/macro-approach-441906-c2/web-app-repo/my-app:blue'
  - './website-blue'

- name: 'gcr.io/cloud-builders/docker'
  id: Push-blue
  args:
  - 'push'
  - 'europe-west1-docker.pkg.dev/macro-approach-441906-c2/web-app-repo/my-app:blue'

- name: 'gcr.io/cloud-builders/docker'
  id: Build-green
  args:
  - 'build'
  - '-t'
  - 'europe-west1-docker.pkg.dev/macro-approach-441906-c2/web-app-repo/my-app:green'
  - './website-green'

- name: 'gcr.io/cloud-builders/docker'
  id: Push-green
  args:
  - 'push'
  - 'europe-west1-docker.pkg.dev/macro-approach-441906-c2/web-app-repo/my-app:green'


- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  entrypoint: 'bash'
  args:
    - '-c'
    - |
         PROJECT=$$(gcloud config get-value core/project)          
         gke-gcloud-auth-plugin --version
         export USE_GKE_GCLOUD_AUTH_PLUGIN=True
         gcloud container clusters get-credentials "gke-cluster" --project "macro-approach-441906-c2"  --zone "europe-west1-b"  
         kubectl apply -f blue.yaml
         kubectl apply -f green.yaml
         kubectl apply -f service-test.yaml


options:
  logging: CLOUD_LOGGING_ONLY

