apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: lgwm-image
        image: europe-west1-docker.pkg.dev/macro-approach-441906-c2/web-app-repo/my-app:green
        ports:
        - containerPort: 80